import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Start Page</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Start Page
        </h1>

        <div className={styles.grid}>
          <Link href="/pin-start">
            <a className={styles.card}>
              <h2>Pin Start &rarr;</h2>
            </a>
          </Link>
          <Link href="/pin-complete">
            <a className={styles.card}>
              <h2>Pin Complete &rarr;</h2>
            </a>
          </Link>
          <Link href="/anvil-start">
            <a className={styles.card}>
              <h2>Anvil Start &rarr;</h2>
            </a>
          </Link>
          <Link href="/anvil-complete">
            <a className={styles.card}>
              <h2>Anvil Complete &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

    </div>
  )
}

export default Home
