import type { NextPage } from 'next'
import Head from 'next/head'
import Link from "next/link";
import styles from '../styles/Home.module.css'

const PinStart: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Start Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Set Your Pin
        </h1>

        <Link href="/pin-complete">
          <a className={styles.card}>
            <h2>Set Pin &rarr;</h2>
          </a>
        </Link>
      </main>
    </div>
  )
}

export default PinStart;
